### ISSUE TITLE
[问题] lsp中作用域搜不到GG

### ISSUE THREAD

**Issue by 565183649** [HdShare/HookGG#2]
是因为它自己隐身了自己吗？按照包名也搜索了下都没有，有具体一点的教程吗？原谅我愚钝

**Comment by HdShare** [comment]
lsp中, HookGG作用域右上角
查看是否有隐藏内容
如隐藏，请取消勾选

**Comment by 565183649** [comment]
谢谢，一个个翻终于在最后找到了，请问模块本身还需要进行什么设置吗

**Comment by HdShare** [comment]
模块本身配置GG修改器包名, 版本, hook的功能即可

**Comment by 565183649** [comment]
怎么查看配置成功了？是修改器里多出了什么功能吗？看起来没什么变化😂

**Comment by HdShare** [comment]
HookGG设置页配置
1.包名是GG修改器包名, 而不是模块包名, 如你上文的 com.r.ojb.ij
2.hook功能要配置, 即FunctionList
3.模块主要功能是输出运行脚本调用功能的日志, 而不是对修改器添加新功能
